const canvas = document.getElementById('game');
const ctx = canvas.getContext('2d');
const N = 13, S = 720 / N;
const $ = id => document.getElementById(id);
let grid, player, enemies, bombs, flames, powerups, score, lives, timeLeft, running, lastTime, enemyTick, timerTick;

function blankGrid() {
  const g = Array.from({length:N}, () => Array(N).fill(0));
  for (let y=0;y<N;y++) for(let x=0;x<N;x++) {
    if(x===0||y===0||x===N-1||y===N-1 || (x%2===0&&y%2===0)) g[y][x]=1;
  }
  const safe = new Set(['1,1','1,2','2,1','11,1','11,2','10,1','11,11','11,10','10,11','7,7']);
  for(let y=1;y<N-1;y++) for(let x=1;x<N-1;x++) if(!g[y][x]&&!safe.has(`${x},${y}`) && Math.random()<.56)g[y][x]=2;
  return g;
}
function reset() {
  grid=blankGrid(); player={x:1,y:1,maxBombs:1,range:2,inv:0}; enemies=[{x:11,y:1,dir:2},{x:11,y:11,dir:3},{x:1,y:11,dir:0},{x:7,y:7,dir:1}];
  bombs=[];flames=[];powerups=[];score=0;lives=3;timeLeft=90;running=true;lastTime=0;enemyTick=0;timerTick=0;updateHud();$('overlay').classList.add('hidden');
}
function updateHud(){ $('score').textContent=String(score).padStart(6,'0'); $('bestScore').textContent=String(Math.max(score,+localStorage.getItem('blastBest')||0)).padStart(6,'0'); $('lives').textContent='● '.repeat(lives).trim()||'—'; $('enemyCount').textContent=String(enemies.length).padStart(2,'0');$('bombStock').innerHTML=`${String(player.maxBombs-bombs.length).padStart(2,'0')} <i>×</i>`;$('range').innerHTML=`${String(player.range).padStart(2,'0')} <i>×</i>`;$('timer').textContent=`${String(Math.floor(timeLeft/60)).padStart(2,'0')}:${String(timeLeft%60).padStart(2,'0')}`; }
function walkable(x,y){return x>=0&&y>=0&&x<N&&y<N&&!grid[y][x]&&!bombs.some(b=>b.x===x&&b.y===y)}
function move(dx,dy){if(!running)return;let nx=player.x+dx,ny=player.y+dy;if(walkable(nx,ny)){player.x=nx;player.y=ny;const p=powerups.findIndex(a=>a.x===nx&&a.y===ny);if(p>=0){const kind=powerups[p].kind;kind==='bomb'?player.maxBombs++:player.range++;powerups.splice(p,1);score+=50;updateHud()}}}
function plant(){if(!running||bombs.length>=player.maxBombs||bombs.some(b=>b.x===player.x&&b.y===player.y))return;bombs.push({x:player.x,y:player.y,fuse:180});updateHud()}
function explode(b){bombs=bombs.filter(x=>x!==b); const cells=[[b.x,b.y]]; for(const[dX,dY]of [[1,0],[-1,0],[0,1],[0,-1]])for(let i=1;i<=player.range;i++){let x=b.x+dX*i,y=b.y+dY*i;if(grid[y][x]===1)break;cells.push([x,y]);if(grid[y][x]===2){grid[y][x]=0;if(Math.random()<.28)powerups.push({x,y,kind:Math.random()<.5?'bomb':'fire'});break;}} flames.push(...cells.map(([x,y])=>({x,y,life:38}))); cells.forEach(([x,y])=>{const chain=bombs.find(q=>q.x===x&&q.y===y);if(chain)explode(chain)});updateHud()}
function hurt(){if(player.inv)return;lives--;player.inv=90;if(!lives){end(false);return}player.x=1;player.y=1;updateHud()}
function end(win){running=false;localStorage.setItem('blastBest',Math.max(score,+localStorage.getItem('blastBest')||0));$('overlayKicker').textContent=win?'SECTOR CLEARED':'RUN TERMINATED';$('overlayTitle').textContent=win?'NICE WORK!':'GAME OVER';$('overlayText').textContent=win?`Score ${String(score).padStart(6,'0')} — the foundry is silent.`:`Final score ${String(score).padStart(6,'0')}. The grid will be waiting.`;$('restartButton').textContent=win?'NEXT RUN ↻':'TRY AGAIN ↻';$('overlay').classList.remove('hidden');updateHud()}
function update(dt){if(!running)return;timerTick+=dt;if(timerTick>1000){timeLeft--;timerTick-=1000;updateHud();if(!timeLeft)end(false)}player.inv=Math.max(0,player.inv-dt/16);bombs.forEach(b=>b.fuse-=dt/16);bombs.filter(b=>b.fuse<=0).slice().forEach(explode);flames.forEach(f=>f.life-=dt/16);flames=flames.filter(f=>f.life>0);if(flames.some(f=>f.x===player.x&&f.y===player.y))hurt();enemyTick+=dt;if(enemyTick>310){enemyTick=0;enemies.forEach(e=>{let choices=[[0,-1],[1,0],[0,1],[-1,0]].filter(([dx,dy])=>walkable(e.x+dx,e.y+dy));if(choices.length){let c=choices[Math.floor(Math.random()*choices.length)];e.x+=c[0];e.y+=c[1]} }); if(enemies.some(e=>e.x===player.x&&e.y===player.y))hurt()}flames.forEach(f=>{for(let i=enemies.length-1;i>=0;i--)if(enemies[i].x===f.x&&enemies[i].y===f.y){enemies.splice(i,1);score+=250;updateHud()}});if(!enemies.length)end(true)}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(x,y,w,h)}
function draw(){ctx.clearRect(0,0,720,720);rect(0,0,720,720,'#262538');for(let y=0;y<N;y++)for(let x=0;x<N;x++){rect(x*S+2,y*S+2,S-4,S-4,(x+y)%2?'#343348':'#303044');if(grid[y][x]===1){rect(x*S,y*S,S,S,'#151522');rect(x*S+5,y*S+5,S-10,S-10,'#585565');rect(x*S+10,y*S+10,S-20,7,'#777483')}else if(grid[y][x]===2){rect(x*S+4,y*S+4,S-8,S-8,'#d85a43');rect(x*S+8,y*S+8,S-16,S-16,'#f37d56');rect(x*S+12,y*S+14,S-24,5,'#bc463b')}}powerups.forEach(p=>{ctx.fillStyle=p.kind==='bomb'?'#ffc433':'#8fe2bc';ctx.beginPath();ctx.arc((p.x+.5)*S,(p.y+.5)*S,S*.22,0,7);ctx.fill();ctx.fillStyle='#20202d';ctx.font='bold 20px sans-serif';ctx.textAlign='center';ctx.fillText(p.kind==='bomb'?'+':'↑',(p.x+.5)*S,(p.y+.5)*S+7)});flames.forEach(f=>{let pulse=1+Math.sin(f.life*.5)*.13;ctx.fillStyle='#ffb72d';ctx.beginPath();ctx.moveTo((f.x+.5)*S,(f.y+.12)*S);ctx.lineTo((f.x+.78)*S,(f.y+.58)*S);ctx.lineTo((f.x+.5)*S,(f.y+.88)*S);ctx.lineTo((f.x+.22)*S,(f.y+.58)*S);ctx.fill();ctx.fillStyle='#fff3b4';ctx.beginPath();ctx.arc((f.x+.5)*S,(f.y+.52)*S,S*.16*pulse,0,7);ctx.fill()});bombs.forEach(b=>{let r=S*(.25+Math.sin(b.fuse*.15)*.035);ctx.fillStyle='#181824';ctx.beginPath();ctx.arc((b.x+.5)*S,(b.y+.55)*S,r,0,7);ctx.fill();ctx.strokeStyle='#ffc433';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo((b.x+.5)*S,(b.y+.28)*S);ctx.lineTo((b.x+.64)*S,(b.y+.16)*S);ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc((b.x+.42)*S,(b.y+.47)*S,r*.2,0,7);ctx.fill()});enemies.forEach(e=>{let cx=(e.x+.5)*S,cy=(e.y+.53)*S;ctx.fillStyle='#8fe2bc';ctx.beginPath();ctx.arc(cx,cy,S*.29,0,7);ctx.fill();ctx.fillStyle='#20202d';ctx.fillRect(cx-S*.13,cy-S*.06,S*.07,S*.1);ctx.fillRect(cx+S*.06,cy-S*.06,S*.07,S*.1);ctx.fillStyle='#59af8a';ctx.fillRect(cx-S*.2,cy+S*.2,S*.4,S*.12)});if(!player.inv||Math.floor(player.inv/8)%2===0){let cx=(player.x+.5)*S,cy=(player.y+.53)*S;ctx.fillStyle='#ffc433';ctx.beginPath();ctx.arc(cx,cy,S*.3,0,7);ctx.fill();ctx.fillStyle='#ff6747';ctx.fillRect(cx-S*.3,cy+S*.07,S*.6,S*.19);ctx.fillStyle='#20202d';ctx.fillRect(cx-S*.13,cy-S*.07,S*.07,S*.1);ctx.fillRect(cx+S*.06,cy-S*.07,S*.07,S*.1)}}
function frame(t){let dt=Math.min(t-lastTime||16,50);lastTime=t;update(dt);draw();requestAnimationFrame(frame)}
addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' ','w','a','s','d'].includes(key))e.preventDefault();if(key==='w'||key==='arrowup')move(0,-1);if(key==='s'||key==='arrowdown')move(0,1);if(key==='a'||key==='arrowleft')move(-1,0);if(key==='d'||key==='arrowright')move(1,0);if(key===' ')plant()});$('restartButton').onclick=reset;$('newGame').onclick=reset;reset();requestAnimationFrame(frame);
